import type { Metadata } from "next";
import {
  Inter,
  Open_Sans,
  Playfair,
  Playfair_Display,
  Playfair_Display_SC,
} from "next/font/google";
import "./globals.scss";
import { CSSProperties } from "react";
import Footer from "./components/footer/Footer";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Virtual Phantom Experience",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={
          {
            "--fontMain": playfair.style.fontFamily,
            "--fontAlt": openSans.style.fontFamily,
          } as CSSProperties
        }
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
